### ISSUE TITLE
Failed to run command in windows 10

### ISSUE THREAD

**Issue by matrixor** [alexarchambault/jupyter-scala#142]
C:\Users\Matrixor>jupyter kernelspec list
Available kernels:
  python3    c:\users\matrixor\appdata\local\programs\python\python35\lib\site-packages\ipykernel\resources
  scala      C:\Users\Matrixor\AppData\Roaming\jupyter\kernels\scala

C:\Users\Matrixor>jupyter console --kernel='scala' --debug
[ZMQTerminalIPythonApp] Searching ['C:\\Users\\Matrixor', 'C:\\Users\\Matrixor\\.jupyter', 'c:\\users\\matrixor\\appdata\\local\\programs\\python\\python35\\etc\\jupyter', 'C:\\ProgramData\\jupyter'] for config files
[ZMQTerminalIPythonApp] Looking for jupyter_config in C:\ProgramData\jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_config in c:\users\matrixor\appdata\local\programs\python\python35\etc\jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_config in C:\Users\Matrixor\.jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_config in C:\Users\Matrixor
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in C:\ProgramData\jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in c:\users\matrixor\appdata\local\programs\python\python35\etc\jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in C:\Users\Matrixor\.jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in C:\Users\Matrixor
[ZMQTerminalIPythonApp] Connection File not found: C:\Users\Matrixor\AppData\Roaming\jupyter\runtime\kernel-4488.json
[ZMQTerminalIPythonApp] Found kernel scala in C:\Users\Matrixor\AppData\Roaming\jupyter\kernels
[ZMQTerminalIPythonApp] Native kernel (python3) available from c:\users\matrixor\appdata\local\programs\python\python35\lib\site-packages\ipykernel\resources
[ZMQTerminalIPythonApp] Starting kernel: ['java', '-noverify', '-jar', 'C:\\Users\\Matrixor\\AppData\\Roaming\\jupyter\\kernels\\scala\\launcher.jar', 'launch', '-r', 'sonatype:releases', '-r', 'sonatype:snapshots', '-i', 'ammonite', '-I', 'ammonite:org.jupyter-scala:ammonite-runtime_2.11.8:0.8.2-2', '-I', 'ammonite:org.jupyter-scala:scala-api_2.11.8:0.4.0', 'org.jupyter-scala:scala-cli_2.11.8:0.4.0', '--', '--id', 'scala', '--name', 'Scala', '--quiet', '--connection-file', 'C:\\Users\\Matrixor\\AppData\\Roaming\\jupyter\\runtime\\kernel-4488.json']
[ZMQTerminalIPythonApp] ERROR | Failed to run command:
['java', '-noverify', '-jar', 'C:\\Users\\Matrixor\\AppData\\Roaming\\jupyter\\kernels\\scala\\launcher.jar', 'launch', '-r', 'sonatype:releases', '-r', 'sonatype:snapshots', '-i', 'ammonite', '-I', 'ammonite:org.jupyter-scala:ammonite-runtime_2.11.8:0.8.2-2', '-I', 'ammonite:org.jupyter-scala:scala-api_2.11.8:0.4.0', 'org.jupyter-scala:scala-cli_2.11.8:0.4.0', '--', '--id', 'scala', '--name', 'Scala', '--quiet', '--connection-file', 'C:\\Users\\Matrixor\\AppData\\Roaming\\jupyter\\runtime\\kernel-4488.json']
    PATH='C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\;D:\\Program\\QuickTime\\QTSystem\\;D:\\Program\\Git\\cmd;C:\\TDM-GCC-64\\bin;D:\\Program\\spark\\bin;D:\\Program\\scala\\bin;C:\\TDM-GCC-64\\bin;C:\\Users\\Matrixor\\AppData\\Local\\Programs\\Python\\Python35\\Scripts\\;C:\\Users\\Matrixor\\AppData\\Local\\Programs\\Python\\Python35\\;C:\\Users\\Matrixor\\AppData\\Local\\Microsoft\\WindowsApps;D:\\Program\\Docker Toolbox'
    with kwargs:
{'stderr': None, 'stdin': -1, 'cwd': None, 'stdout': None}

Traceback (most recent call last):
  File "c:\users\matrixor\appdata\local\programs\python\python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\matrixor\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Matrixor\AppData\Local\Programs\Python\Python35\Scripts\jupyter-console.EXE\__main__.py", line 9, in <module>
  File "c:\users\matrixor\appdata\local\programs\python\python35\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "c:\users\matrixor\appdata\local\programs\python\python35\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-114>", line 2, in initialize
  File "c:\users\matrixor\appdata\local\programs\python\python35\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\users\matrixor\appdata\local\programs\python\python35\lib\site-packages\jupyter_console\app.py", line 137, in initialize
    self.init_shell()
  File "c:\users\matrixor\appdata\local\programs\python\python35\lib\site-packages\jupyter_console\app.py", line 105, in init_shell
    JupyterConsoleApp.initialize(self)
  File "c:\users\matrixor\appdata\local\programs\python\python35\lib\site-packages\jupyter_client\consoleapp.py", line 334, in initialize
    self.init_kernel_manager()
  File "c:\users\matrixor\appdata\local\programs\python\python35\lib\site-packages\jupyter_client\consoleapp.py", line 288, in init_kernel_manager
    self.kernel_manager.start_kernel(**kwargs)
  File "c:\users\matrixor\appdata\local\programs\python\python35\lib\site-packages\jupyter_client\manager.py", line 243, in start_kernel
    **kw)
  File "c:\users\matrixor\appdata\local\programs\python\python35\lib\site-packages\jupyter_client\manager.py", line 189, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "c:\users\matrixor\appdata\local\programs\python\python35\lib\site-packages\jupyter_client\launcher.py", line 123, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "c:\users\matrixor\appdata\local\programs\python\python35\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "c:\users\matrixor\appdata\local\programs\python\python35\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by matrixor** [comment]
My fault :) typo kernal to kernel
