### ISSUE TITLE
jupyter-scala crashing repl

### ISSUE THREAD

**Issue by sbromberger** [alexarchambault/jupyter-scala#67]
installed via `curl -L -o jupyter-scala https://git.io/vzhRi && chmod +x jupyter-scala && ./jupyter-scala`

```
phase:scala me$ jupyter console --kernel scala211
Jupyter Console 4.1.1


In [1]: val a = 5
WARNING: The kernel did not respond to an is_complete_request. Setting `use_kernel_is_complete` to False.
a: Int = 5
Traceback (most recent call last):
  File "/Users/me/Library/Python/2.7/bin/jupyter-console", line 11, in <module>
    sys.exit(main())
  File "/Users/me/Library/Python/2.7/lib/python/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/me/Library/Python/2.7/lib/python/site-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/Users/me/Library/Python/2.7/lib/python/site-packages/jupyter_console/app.py", line 152, in start
    self.shell.mainloop()
  File "/Users/me/Library/Python/2.7/lib/python/site-packages/jupyter_console/interactiveshell.py", line 483, in mainloop
    self.interact(display_banner=display_banner)
  File "/Users/me/Library/Python/2.7/lib/python/site-packages/jupyter_console/interactiveshell.py", line 659, in interact
    self.run_cell(source_raw)
  File "/Users/me/Library/Python/2.7/lib/python/site-packages/jupyter_console/interactiveshell.py", line 203, in run_cell
    self.handle_execute_reply(msg_id, timeout=0.05)
  File "/Users/me/Library/Python/2.7/lib/python/site-packages/jupyter_console/interactiveshell.py", line 221, in handle_execute_reply
    status = content['status']
KeyError: 'status'
```

**Comment by alexarchambault** [comment]
That should be fixed by https://github.com/alexarchambault/jupyter-kernel/commit/63f64f3c9adadeece938e0c5c35af9cc63ab63aa, which is used by the master of jupyter-scala... but not included in the latest release. I'll do one soon (possibly tomorrow).

**Comment by alexarchambault** [comment]
Btw, if you prefer the console to notebooks, I'd recommend using directly [ammonium](https://github.com/alexarchambault/ammonium), which has nice features from Ammonite (syntax-highlighting of the input in particular). And doesn't suffer this issue.

**Comment by sbromberger** [comment]
Thank you, @alexarchambault - I need both, since I'm using Atom/Hydrogen as well as the console.

**Comment by sbromberger** [comment]
Confirmed fixed in latest master. Thank you, @alexarchambault !
